version: '3'

services:
  db:
    image: mysql:5.7
    container_name: favourites_db
    hostname: favourites_db
    ports:
      - '3306:3306'
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'favourites_svc'
      MYSQL_USER: 'favourites_svc'
      MYSQL_PASSWORD: '123456'
    networks:
      - favourites_networks

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: favourites_admin
    hostname: favourites_admin
    ports:
      - 8000:80
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: 'favourites_svc'
    networks:
      - favourites_networks

networks:
  favourites_networks:
    driver: bridge